services:
  db:
    image: postgres:15-alpine
    container_name: naumen_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: naumen_case
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: naumen_backend
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/naumen_case
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update # Для хакатона норм, потом смените на validate
      # Жесткий лимит памяти для Java, чтобы не убила VPS
      JAVA_OPTS: "-Xmx512m -Xms256m"
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: naumen_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "81:80"
    # SSL сертификаты прокидываем из ОС сервера внутрь контейнера Nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  db_data:
