ALTER TABLE users ADD COLUMN photo_url VARCHAR(1024);
ALTER TABLE users ADD COLUMN team VARCHAR(255);
ALTER TABLE users ADD COLUMN mood_level INTEGER NOT NULL DEFAULT 3;
ALTER TABLE users ADD COLUMN progress_block_one INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN progress_block_two INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN progress_block_three INTEGER NOT NULL DEFAULT 0;
