-- Seed data: 50 employees for local/demo environment.
-- Test password hash for all seeded users (bcrypt, do not use in production):
-- password_hash = $2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy

INSERT INTO users (email, password_hash, full_name, department, role, is_active, created_at)
VALUES
    ('employee01@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Artem Sokolov', 'Backend Platform', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '3 days'),
    ('employee02@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Elena Morozova', 'Frontend Engineering', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '5 days'),
    ('employee03@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Ivan Petrov', 'Quality Assurance', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '7 days'),
    ('employee04@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Natalia Smirnova', 'Business Analysis', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '9 days'),
    ('employee05@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Pavel Lebedev', 'Data Engineering', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '11 days'),
    ('employee06@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Daria Volkova', 'Customer Success', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '13 days'),
    ('employee07@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Sergey Orlov', 'DevOps', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '15 days'),
    ('employee08@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Anna Belova', 'Product Management', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '17 days'),
    ('employee09@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Maksim Fedorov', 'Backend Platform', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '19 days'),
    ('employee10@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Olga Ershova', 'Frontend Engineering', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '21 days'),
    ('employee11@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Roman Kuznetsov', 'Quality Assurance', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '23 days'),
    ('employee12@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Yulia Vinogradova', 'Business Analysis', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '25 days'),
    ('employee13@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Kirill Novikov', 'Data Engineering', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '27 days'),
    ('employee14@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Tatiana Nikitina', 'Customer Success', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '29 days'),
    ('employee15@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Denis Gromov', 'DevOps', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '31 days'),
    ('employee16@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Marina Sorokina', 'Product Management', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '33 days'),
    ('employee17@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Alexey Karpov', 'Backend Platform', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '35 days'),
    ('employee18@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Svetlana Makarova', 'Frontend Engineering', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '37 days'),
    ('employee19@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Vladimir Antonov', 'Quality Assurance', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '39 days'),
    ('employee20@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Irina Kiseleva', 'Business Analysis', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '41 days'),
    ('employee21@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Nikolay Egorov', 'Data Engineering', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '43 days'),
    ('employee22@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Veronika Abramova', 'Customer Success', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '45 days'),
    ('employee23@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Andrey Safonov', 'DevOps', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '47 days'),
    ('employee24@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Maria Biryukova', 'Product Management', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '49 days'),
    ('employee25@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Ilya Zaitsev', 'Backend Platform', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '51 days'),
    ('employee26@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Kristina Guseva', 'Frontend Engineering', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '53 days'),
    ('employee27@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Timur Danilov', 'Quality Assurance', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '55 days'),
    ('employee28@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Lidia Bogdanova', 'Business Analysis', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '57 days'),
    ('employee29@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Grigory Tarasov', 'Data Engineering', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '59 days'),
    ('employee30@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Alina Sokolova', 'Customer Success', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '61 days'),
    ('employee31@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Yaroslav Mironov', 'DevOps', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '63 days'),
    ('employee32@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Polina Trofimova', 'Product Management', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '65 days'),
    ('employee33@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Mikhail Soloviev', 'Backend Platform', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '67 days'),
    ('employee34@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Ekaterina Koroleva', 'Frontend Engineering', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '69 days'),
    ('employee35@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Gleb Komarov', 'Quality Assurance', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '71 days'),
    ('employee36@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Inna Serova', 'Business Analysis', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '73 days'),
    ('employee37@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Ruslan Belyaev', 'Data Engineering', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '75 days'),
    ('employee38@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Larisa Melnikova', 'Customer Success', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '77 days'),
    ('employee39@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Stanislav Zhukov', 'DevOps', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '79 days'),
    ('employee40@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Oksana Pavlova', 'Product Management', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '81 days'),
    ('employee41@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Fyodor Matveev', 'Backend Platform', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '83 days'),
    ('employee42@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Nina Romanova', 'Frontend Engineering', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '85 days'),
    ('employee43@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Yegor Belkin', 'Quality Assurance', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '87 days'),
    ('employee44@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Galina Osipova', 'Business Analysis', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '89 days'),
    ('employee45@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Vadim Kalinin', 'Data Engineering', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '91 days'),
    ('employee46@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Alyona Uvarova', 'Customer Success', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '93 days'),
    ('employee47@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Oleg Grachev', 'DevOps', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '95 days'),
    ('employee48@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Sofia Kudryavtseva', 'Product Management', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '97 days'),
    ('employee49@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Konstantin Voronov', 'Backend Platform', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '99 days'),
    ('employee50@naumen.ru', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Zhanna Filatova', 'Frontend Engineering', 'ROLE_EMPLOYEE', TRUE, NOW() - INTERVAL '101 days');
